# Generated by Django 3.2 on 2022-02-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='description_short',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
