# Generated by Django 3.2 on 2022-02-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
    ]
